name: Publish Fabric to WinGet on Release

on:
  # Triggered via repository_dispatch from upstream
  repository_dispatch:
    types: [fabric-winget-release]

  # Manual trigger as backup
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., v1.4.302)"
        required: true
        type: string
      url:
        description: "Release URL (optional)"
        required: false
        type: string

jobs:
  publish-to-winget:
    runs-on: ubuntu-latest

    steps:
      - name: Extract release information
        id: release_info
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT
            echo "url=${{ github.event.client_payload.url }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
            echo "url=${{ github.event.inputs.url }}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Get Windows assets from release
        id: assets
        run: |
          tag="${{ steps.release_info.outputs.tag }}"
          version=$(echo "$tag" | sed 's/^v//')

          echo "Publishing version: $version"
          echo "Using tag: $tag"

          # Get release info from danielmiessler/fabric
          release_info=$(curl -s "https://api.github.com/repos/danielmiessler/fabric/releases/tags/$tag")

          # Extract Windows asset URLs
          urls=$(echo "$release_info" | jq -r '.assets[] | select(.name | test("\\.(exe|msi|msix|appx)$")) | .browser_download_url' | tr '\n' ' ')

          if [ -z "$urls" ]; then
            echo "No Windows installer assets found for $tag, skipping..."
            exit 0
          fi

          echo "Found Windows assets: $urls"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "urls=$urls" >> $GITHUB_OUTPUT

      - name: Update WinGet manifest
        uses: michidk/run-komac@v2
        with:
          args: "update danielmiessler.Fabric --version ${{ steps.assets.outputs.version }} --urls ${{ steps.assets.outputs.urls }} --submit"
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_TOKEN }}
